// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5v0X3JwDl7pe6J0nG7p3ONDlpDXK-sqY',
    appId: '1:683237863646:web:983b1cc888f07aed1a124f',
    messagingSenderId: '683237863646',
    projectId: 'grooming-day-49863',
    authDomain: 'grooming-day-49863.firebaseapp.com',
    storageBucket: 'grooming-day-49863.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByx7sIlOWZ5W7b50cCGg4eLSkzD3UxNfU',
    appId: '1:683237863646:android:65aecf73286858c31a124f',
    messagingSenderId: '683237863646',
    projectId: 'grooming-day-49863',
    storageBucket: 'grooming-day-49863.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtxK_JQ3xCc4zwqXskpWkbdV3SsanyNSk',
    appId: '1:683237863646:ios:e36688954730471b1a124f',
    messagingSenderId: '683237863646',
    projectId: 'grooming-day-49863',
    storageBucket: 'grooming-day-49863.firebasestorage.app',
    iosBundleId: 'com.example.groomingDay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtxK_JQ3xCc4zwqXskpWkbdV3SsanyNSk',
    appId: '1:683237863646:ios:e36688954730471b1a124f',
    messagingSenderId: '683237863646',
    projectId: 'grooming-day-49863',
    storageBucket: 'grooming-day-49863.firebasestorage.app',
    iosBundleId: 'com.example.groomingDay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5v0X3JwDl7pe6J0nG7p3ONDlpDXK-sqY',
    appId: '1:683237863646:web:acd77cc4c2e903941a124f',
    messagingSenderId: '683237863646',
    projectId: 'grooming-day-49863',
    authDomain: 'grooming-day-49863.firebaseapp.com',
    storageBucket: 'grooming-day-49863.firebasestorage.app',
  );
}
